name: Release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependency-Check CLI
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.1.0/dependency-check-9.1.0-release.zip 
          unzip dependency-check-9.1.0-release.zip 
          rm dependency-check-9.1.0-release.zip 
          chmod +x dependency-check/bin/dependency-check.sh 

      - name : test dependency-check
        run : |
          ./dependency-check/bin/dependency-check.sh --scan . --format HTML --project SHS --out reports --nvdApiKey "3fd85911-12f9-474d-8081-a52d69747465"

      - name : Upload the Dependency-Check report
        uses : actions/upload-artifact@v2
        with :
          name : dependency check-report
          path : reports/dependency-check-report.html






