name: Release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependency-Check CLI
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.1.0/dependency-check-9.1.0-release.zip 
          unzip dependency-check-9.1.0-release.zip 
          rm dependency-check-9.1.0-release.zip 
          chmod +x dependency-check/bin/dependency-check.sh 
      - name: make dir for reports
        run: mkdir reports

      - name: test dependency-check
        run: |
          ./dependency-check/bin/dependency-check.sh --scan . --format HTML --format JSON -out reports --dbDriverName "org.postgresql.Driver" --connectionString "jdbc:postgresql://b79a-2001-818-e80b-f600-7c51-84b8-d454-2d48.ngrok-free.app/" --dbUser "dcclient" --dbPassword "dev02" --dbDriverPath "./driver/postgresql-42.6.0.jar" -n
      - name : Upload the Dependency-Check report
        uses : actions/upload-artifact@v2
        with :
          name : dependency check-report
          path : reports/dependency-check-report.html






